export const bookList = [
  {
    id: '0000',
    image: './images/bhagavad-gita.jpg',
    title: 'The Bhagvahad Gita',
    author: 'Anonymous',
    link: 'https://amzn.to/3JcfdaM',
    isRead: 'Yes'
  },
  {
    id: '0001',
    image: './images/zenmind.jpg',
    title: 'Zen Mind, Beginner\'s Mind',
    author: 'Shunryu Suzuki',
    link: 'https://amzn.to/3JcddiM',
  },
  {
    id: '0002',
    image: './images/eachmoment.jpg',
    title: 'Each Moment is the Universe',
    author: 'Dainin Katagiri Roshi',
    link: 'https://amzn.to/3NP6dfi',
  },
  {
    id: '0003',
    image: './images/miracleofmindfulness.jpg',
    title: 'The Miracle of Mindfulness',
    author: 'Thich Nhat Hanh',
    link: 'https://amzn.to/3vgHx7d',
  },
  {
    id: '0004',
    image: './images/wayofzen.jpg',
    title: 'What is Zen?',
    author: 'Alan Watts',
    link: 'https://amzn.to/36VJnSE',
  },
  {
    id: '0005',
    image: './images/essentialteachings.jpg',
    title: 'The Essential Teachings of Zen Master Hakuin',
    author: 'Norman Waddell',
    link: 'https://amzn.to/3r5OCWM',
  },
  {
    id: '0006',
    image: './images/dreamfantasy.jpg',
    title: 'Like a Dream, Like a Fantasy',
    author: 'Nyogen Senzaki',
    link: 'https://amzn.to/3DKrfqN',
  },
  {
    id: '0007',
    image: './images/taoofpooh.jpg',
    title: 'The Tao of Pooh & The Te of Piglet',
    author: 'Benjamin Hoff',
    link: 'https://amzn.to/3j6SEcT',
  },
  {
    id: '0008',
    image: './images/taoteching.jpg',
    title: 'Tao Te Ching',
    author: 'Lao Tzu',
    link: 'https://amzn.to/3uXhzVV',
  },
  {
    id: '0009',
    image: './images/chuangtzu.jpg',
    title: 'The Book of Chuang Tzu',
    author: 'Chuang Tzu',
    link: 'https://amzn.to/3uXi967',
  },
]